# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'MN Accounting',
    'version': '1.0.1',
    'category': 'Accounting',
    'sequence': 20,
    'author': 'Daramaa Managewall LLC',
    'summary': 'Changed by Mongolian Accounting',
    'description': "",
    'depends': ['account','mw_base','branch','base','account_budget','web_tree_dynamic_colored_field','account_accountant','account_reports','mw_html_finance_report'],#'account_cancel',
    'data': [
        'security/account_security.xml',
        'security/ir.model.access.csv',
        'wizard/import_bank_statement_view.xml',
        'wizard/account_bank_line_change_view.xml',
        'wizard/account_bank_report_view.xml',
        'wizard/account_move_print_view.xml',
        'wizard/partial_bank_confirm_view.xml',
        'wizard/bank_payment_match_view.xml',
        'views/account_bank_statement_import_view.xml',
        'views/account_view.xml',
        'views/account_bank_statement_view.xml',
        'report/account_cash_report_view.xml',
        'report/account_financial_report_view.xml',
        'report/account_transaction_balance_view.xml',
        'report/account_income_statement_view.xml',
        'report/account_transaction_balance_pivot_view.xml',
        'report/account_payment_pivot_view.xml',
        'report/account_partner_balance_view.xml',
        'wizard/account_chart_view.xml',
        'wizard/account_transaction_balance_view.xml',
        'wizard/account_balance_sheet_view.xml',
        'wizard/account_income_statement_view.xml',
        'wizard/account_transaction_balance_view_wizard_view.xml',
        'wizard/account_income_statement_view_wizard_view.xml',
        'wizard/account_partner_ledger_view.xml',
        'wizard/account_payable_account_detail_view.xml',
        'wizard/account_payment_report_view.xml',
        'wizard/account_vat_report_view.xml',
        'views/account_move_import_view.xml',
        'views/account_purchase_stock_match_view.xml',
        'wizard/account_currency_equalization_view.xml',
        'wizard/account_cash_payment_report_view.xml',
        'wizard/account_cashflow_report_view.xml',
        'views/report_invoice.xml',
        'wizard/account_payable_aged_date_report_view.xml',
        'wizard/pos_box.xml',
        'wizard/account_partner_balance_view_wizard_view.xml',
        'wizard/account_sale_reconcile_wizard_view.xml',
        'wizard/account_sales_partner_ledger_view.xml',
        'report/account_statement_report_view.xml',
        'wizard/account_general_journal_view.xml',
        'views/widget_path.xml',
        'views/res_partner_inherit_view.xml'
        ],
    # 'demo': [
    # ],

    'website': 'http://managewall.mn',
    'installable': True,
    # 'auto_install': False,
    'qweb': ['static/src/xml/custom_templates.xml'],
}
